
spring:
  application:
    name: scan-job
  #Data source configuration
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.9.191:3306/scan_${profile}?useUnicode=true&characterEncoding=utf-8&useSSL=false&useTimezone=true&serverTimezone=GMT%2B8&allowMultiQueries=true
    username: ENC(bpshgjWOgn2d+oGmSTBPNA==)
    password: ENC(bpshgjWOgn2d+oGmSTBPNA==)
  #ES index configuration
  elasticsearch:
    high-level-client:
      hosts: 192.168.120.103,192.168.120.104,192.168.120.105
      port: 9200
      schema: http
      username: ENC(VME69JEYLfmUXi3KuDQTWA==)
      password: ENC(A6E/VrNrulxXUK7GSjlmiN7NqxZV5P6o)
    index:
      blockIndexName: ${turn.es-namespace}_block
      transactionIndexName: ${turn.es-namespace}_transaction
      delegationIndexName: ${turn.es-namespace}_delegation
      nodeOptIndexName: ${turn.es-namespace}_nodeopt
      delegationRewardIndexName: ${turn.es-namespace}_delegation_reward
      transferTxIndexName: ${turn.es-namespace}_transfer_tx
      erc20TxIndexName: ${turn.es-namespace}_erc20_tx
      erc721TxIndexName: ${turn.es-namespace}_erc721_tx
      erc1155TxIndexName: ${turn.es-namespace}_erc1155_tx
# MyBatis configuration (note: must correspond to the path of the mapper mapping xml file)
mybatis:
  mapper-locations: classpath*:mapper/*.xml, classpath*:custommapper/*.xml
  # Entity category name configuration (note: the path to the corresponding entity class)
  type-aliases-package: com.turn.browser.dao.entity
# Currently activated configuration name (please do not modify it)
profile: turn
#Turn related configurations
turn:
  #Address HRP prefix
  addressPrefix:lat
  # Amount display unit
  valueUnit: TURN
  # Number of parallel decoding threads for transaction input parameters
  txLogDecodeThreadNum: 200
  # Web3j access address
  web3j:
    #HTTPorWS
    protocol: WS
    addresses: 192.168.120.151:7789,192.168.120.151:7790
  # How many consecutive periods can the statistical annualized rate of pledge nodes take at most?
  maxSettlePeriodCount4AnnualizedRateStat: 4
  #TurnTotal initial circulation (TURN)
  initIssueAmount: 10000000000
  #Fixed issuance ratio every year
  addIssueRate: 0.025
  #The proportion of additional issuance allocated to the incentive pool each year
  incentiveRateFromIssue: 0.8
  #How many blocks are rolled back in each consensus round is the time to elect the next round of validators
  electionBackwardBlockCount: 20
  #The amount of money the Calculator Foundation will fill into the incentive pool within 10 years: <year - subsidy amount (TURN)>
  foundationSubsidies: {
    '1':62215742.00000000,
    '2':55965742.00000000,
    '3':49559492.00000000,
    '4':42993086.00000000,
    '5':36262520.00000000,
    '6':29363689.00000000,
    '7':22292388.00000000,
    '8':15044304.00000000,
    '9':7615018.00000000
  }
  # Default pledge amount of initial built-in node (TURN)
  defaultStakingLockedAmount: 150000
  #Block maximum gas limit
  maxBlockGasLimit: 201600000
  #Proposal url parameter template
  proposalUrlTemplate: https://github.com/Turnnetwork/PIPs/blob/master/PIPs/PIP-%s.md
  #Proposal pip_num parameter template
  proposalPipNumTemplate: PIP-%s
  #keysBaseURL
  keyBase: https://keybase.io/
  #keyBase api
  keyBaseApi: _/api/1.0/user/lookup.json?key_suffix=
  #chainid
  chainId: 210425
  #Index query paging parameter configuration during synchronization
  paging:
    erc20-transaction:
      pageSize: 2000
      pageCount: 250
  #Esindex namespace
  es-namespace: browser_${profile}
task:
  #Maximum number of addresses allowed to be updated
  maxAddressCount: 5004
  #Maximum number of locked balances for each batch query  maxBatchSize: 100
#Log configuration
logging:
  #Log level
  level:
    org.springframework: error
    com.turn.browser.task: debug
xxl:
  job:
    admin:
      #Deployment and address of dispatch center
      addresses: http://10.0.0.34:8060/xxl-job-admin
    #Dispatch center communication TOKEN
    accessToken: ENC(IZf5O7X2oiVstkwHNZUxEhPzDKInPh0TexHqj7b4YY39c10DzZaDqqQYWoSw8l2q)
    #Number of days to save dispatch center log files
    logretentiondays: 90
    executor:
      #ExecutorAppName
      appname: turn-scan-job
      IP: 192.168.21.114
      #Executor port number
      port: 9997
      #Executor running log file storage disk path
      logpath: ./logs/jobhandler
      #Number of days to save executor log files
      logretentiondays: 90
apollo:
  bootstrap:
    # Whether to enable Apollo
    enabled: false