package com.turn.browser.dao.mapper;

import com.github.pagehelper.Page;
import com.turn.browser.dao.entity.Bubble;
import com.turn.browser.dao.entity.BubbleExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface BubbleMapper {
    long countByExample(BubbleExample example);

    int deleteByExample(BubbleExample example);

    int deleteByPrimaryKey(Long id);

    int insert(Bubble record);

    int insertSelective(Bubble record);

    List<Bubble> selectByExample(BubbleExample example);

    Bubble selectByPrimaryKey(Long id);

    int updateByExampleSelective(@Param("record") Bubble record, @Param("example") BubbleExample example);

    int updateByExample(@Param("record") Bubble record, @Param("example") BubbleExample example);

    int updateByPrimaryKeySelective(Bubble record);

    int updateByPrimaryKey(Bubble record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bubble
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int batchInsert(@Param("list") List<Bubble> list);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bubble
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int batchInsertSelective(@Param("list") List<Bubble> list, @Param("selective") Bubble.Column ... selective);

    Page<Bubble> selectListByExample(BubbleExample bubbleExample);
}