package com.turn.browser.dao.mapper;

import com.github.pagehelper.Page;
import com.turn.browser.dao.entity.MicroNode;
import com.turn.browser.dao.entity.MicroNodeExample;

import java.math.BigInteger;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface MicroNodeMapper {
    long countByExample(MicroNodeExample example);

    int deleteByExample(MicroNodeExample example);

    int deleteByPrimaryKey(String nodeId);

    int insert(MicroNode record);

    int insertSelective(MicroNode record);

    List<MicroNode> selectByExample(MicroNodeExample example);

    MicroNode selectByPrimaryKey(String nodeId);

    int updateByExampleSelective(@Param("record") MicroNode record, @Param("example") MicroNodeExample example);

    int updateByExample(@Param("record") MicroNode record, @Param("example") MicroNodeExample example);

    int updateByPrimaryKeySelective(MicroNode record);

    int updateByPrimaryKey(MicroNode record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table micro_node
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int batchInsert(@Param("list") List<MicroNode> list);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table micro_node
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int batchInsertSelective(@Param("list") List<MicroNode> list, @Param("selective") MicroNode.Column ... selective);

    BigInteger countStakingAmount();

    Page<MicroNode> selectListByExample(MicroNodeExample microNodeExample);
}