package com.turn.browser.dao.mapper;

import com.turn.browser.dao.entity.Round;
import com.turn.browser.dao.entity.RoundExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface RoundMapper {
    long countByExample(RoundExample example);

    int deleteByExample(RoundExample example);

    int deleteByPrimaryKey(Long id);

    int insert(Round record);

    int insertSelective(Round record);

    List<Round> selectByExample(RoundExample example);

    Round selectByPrimaryKey(Long id);

    int updateByExampleSelective(@Param("record") Round record, @Param("example") RoundExample example);

    int updateByExample(@Param("record") Round record, @Param("example") RoundExample example);

    int updateByPrimaryKeySelective(Round record);

    int updateByPrimaryKey(Round record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table round
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int batchInsert(@Param("list") List<Round> list);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table round
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int batchInsertSelective(@Param("list") List<Round> list, @Param("selective") Round.Column ... selective);

    void endRound(@Param("roundId") Long roundId, @Param("gameId") Long gameId);
}