
spring:
  application:
    name: scan-subchain
  #Data source configuration
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.31.114:12012/scan_${profile}?useUnicode=true&characterEncoding=utf-8&useSSL=false&useTimezone=true&serverTimezone=GMT%2B8&allowMultiQueries=true
    username: qiliu
    password: qiliu123456
    druid:
      # Configuration information of connection pool
      #Initialize size, minimum, maximum
      initial-size: 5
      min-idle: 5
      maxActive: 20
      # Configure the timeout to wait for a connection
      maxWait: 60000
      # Configure the interval between detection and detection of idle connections that need to be closed. The unit is milliseconds.
      timeBetweenEvictionRunsMillis: 60000
      # Configure the minimum survival time of a connection in the pool, in milliseconds
      minEvictableIdleTimeMillis: 300000
      validationQuery: SELECT 1 FROM DUAL
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      # Turn on PSCache and specify the size of PSCache on each connection
      poolPreparedStatements: true
      maxPoolPreparedStatementPerConnectionSize: 20
      # Configure the filters for monitoring and statistics interception. After removing them, the monitoring interface SQL cannot collect statistics. 'wall' is used for firewalls.
      filters: stat
      filter:
        config: true
        # Enable status monitoring of druiddatasource
        stat:
          enabled: true
          db-type: mysql
          # Enable slow sql monitoring. If it exceeds 2 seconds, it will be considered as slow sql and recorded in the log.
          log-slow-sql: true
          slow-sql-millis: 500
          merge-sql: true
      # Configure DruidStatFilter
      web-stat-filter:
        enabled: true
        url-pattern: /*
        exclusions: '*.js,*.gif,*.jpg,*.bmp,*.png,*.css,*.ico,/druid/*'
      # Configure DruidStatViewServlet
      stat-view-servlet:
        # Whether to enable StatViewServlet (monitoring page), the default value is false (considering security issues, it is not enabled by default. If you need to enable it, it is recommended to set a password or whitelist to ensure security)
        enabled: true
        url-pattern: /druid/*
        # IP whitelist (if not configured or empty, all access is allowed)
        # allow: 127.0.0.1,192.168.46.120
        # IP blacklist (when common, deny takes precedence over allow)
        # deny: 192.168.46.121
        # Disable the "Reset All" function on HTML pages
        reset-enable: false
        # log-in name
        login-username: admin
        # login password
        login-password: 123456
        allow: ""
        deny: ""

  #Redis key configuration
  redis:
    password: "ffca@sn!u934"
    database: 0
    cluster:
      max-redirects: 3
      nodes: 192.168.31.115:6381,192.168.31.115:6382,192.168.31.115:6383,192.168.31.115:6384,192.168.31.115:6385,192.168.31.115:6386
    key:
      #How many pieces of data can be stored at most?
      max-item: 500000
      #Block list
      blocks: ${turn.redis-namespace}:blocks
      #Transaction list
      transactions: ${turn.redis-namespace}:transactions
      #Statistics
      networkStat: ${turn.redis-namespace}:networkStat
      #Internal transfer transaction
      transferTx: ${turn.redis-namespace}:transferTx
      #erc20trade
      erc20Tx: ${turn.redis-namespace}:erc20Tx
      #erc721 Transaction
      erc721Tx: ${turn.redis-namespace}:erc721Tx
      #erc1155 Transaction
      erc1155Tx: ${turn.redis-namespace}:erc1155Tx
      #Joined games list
      addrGames: ${turn.redis-namespace}:addrGames
      #bubble information
      bubbleInfo: ${turn.redis-namespace}:bubbleInfo
  #ES index configuration
  elasticsearch:
    high-level-client:
      hosts: 192.168.31.115:19200,192.168.31.115:29200,192.168.31.115:39200
      port: 19200
      schema: http
      username:
      password:
    index:
      blockIndexName: ${turn.es-namespace}_block
      transactionIndexName: ${turn.es-namespace}_transaction
      delegationIndexName: ${turn.es-namespace}_delegation
      nodeOptIndexName: ${turn.es-namespace}_nodeopt
      delegationRewardIndexName: ${turn.es-namespace}_delegation_reward
      transferTxIndexName: ${turn.es-namespace}_transfer_tx
      erc20TxIndexName: ${turn.es-namespace}_erc20_tx
      erc721TxIndexName: ${turn.es-namespace}_erc721_tx
      erc1155TxIndexName: ${turn.es-namespace}_erc1155_tx
      microNodeOptIndexName: ${turn.es-namespace}_micro_node_opt
      subChainTxIndexName: ${turn.es-namespace}_sub_chain_tx
scan:
  kafka:
    producer:
      # Client ID
      client-id: usafe-sync-${spring.profiles.active}-producer
      # Kafka server
      bootstrap-servers: 192.168.31.115:19092,192.168.31.115:29092,192.168.31.115:39092
      # To open a transaction, it must be sent in the method that opens the transaction, otherwise an error will be reported
      transaction-id-prefix: usafe-sync-${spring.profiles.active}-tx-
      # After an error occurs, the number of message retransmissions must be set greater than 0 to open a transaction.
      retries: 3
      # acks=0: The producer will not wait for any response from the server before successfully writing the message
      # acks=1: As long as the leader node of the cluster receives the message, the producer will receive a successful response from the server
      # acks=all: Only when all nodes participating in replication receive the message, the producer will receive a successful response from the server
      # When starting a transaction, it must be set to all
      acks: all
      # When multiple messages need to be sent to the same partition, the producer will put them in the same batch. This parameter specifies the memory size that can be used by a batch, calculated in bytes.
      batch size: 4096
      # Size of producer memory buffer
      buffer-memory: 1024000
      # Message compression: none, lz4, gzip, snappy, default is none
      compression-type: gzip
      # Even if the data does not reach 16KB, this batch will be sent out
      linger-ms: 5000
      #Maximum size of each message
      max-request-size: 1048576
      # The maximum blocking time of KafkaProducer.send() and partitionsFor() methods in ms
      max-block-ms: 6000
    topic:
      partition: 3
      sub-chain-tx: scan-${spring.profiles.active}-sub-chain-tx
# MyBatis configuration (note: must correspond to the path of the mapper mapping xml file)
mybatis:
  mapper-locations: classpath*:mapper/*.xml, classpath*:custommapper/*.xml
  # Entity category name configuration (note: the path to the corresponding entity class)
  type-aliases-package: com.turn.browser.dao.entity
profile: platon
# The size of the memory ring buffer must be an exponential multiple of 2
disruptor:
  queue:
    # Block event ring buffer size
    blockBufferSize: 1024
    #Collect event ring buffer size
    collectionBufferSize: 1024
    #Data supplement ring buffer size
    complementBufferSize: 1024
    # gas price estimates message ring buffer size
    gasEstimateBufferSize: 1024
    #Data persistence ring buffer size
    persistenceBufferSize: 1024
    #How many to process each time
    persistenceBatchSize: 10
#Log configuration
logging:
  #Log level
  level:
    org.springframework: info
    org.springframework.retry: info
    com.turn.browser: info
    com.turn.browser.bootstrap: info
    com.turn.browser.collection: info
    com.turn.browser.collection.queue.handler: info
    com.turn.browser.common: info
    com.turn.browser.complement: info
    com.turn.browser.complement.handler: info
    com.turn.browser.complement.converter: info
    com.turn.browser.persistence: info
    com.turn.browser.persistence.handler: info
    com.turn.browser.persistence.queue.handler: info
    com.turn.browser.task: info
#Turn related configuration
turn:
  #Address HRP prefix
  addressPrefix: turn
  # Amount display unit
  valueUnit: turn
  # Number of parallel decoding threads for transaction input parameters
  txLogDecodeThreadNum: 200
  # Web3j access address
  web3j:
    #HTTPorWS
    protocol: WS
    addresses: 10.32.165.85:6790
  # How many consecutive periods can the statistical annualized rate of pledge nodes take at most?
  maxSettlePeriodCount4AnnualizedRateStat: 4
  #TURN Total Initial Circulation Volume (TURN)
  initIssueAmount: 10000000000
  #Fixed issuance ratio every year
  addIssueRate: 0.025
  #The proportion of additional issuance allocated to the incentive pool each year
  incentiveRateFromIssue: 0.8
  #How many blocks are rolled back in each consensus round is the time to elect the next round of validators
  electionBackwardBlockCount: 20
  #The amount of money the Calculator Foundation will fill into the incentive pool within 10 years: <year - subsidy amount (TURN)>
  foundationSubsidies: {
    '1':62215742.00000000,
    '2':55965742.00000000,
    '3':49559492.00000000,
    '4':42993086.00000000,
    '5':36262520.00000000,
    '6':29363689.00000000,
    '7':22292388.00000000,
    '8':15044304.00000000,
    '9':7615018.00000000
  }
  # Default pledge amount of initial built-in node (TURN)
  defaultStakingLockedAmount: 150000
  #Block maximum gas limit
  maxBlockGasLimit: 201600000
  #Proposal url parameter template
  proposalUrlTemplate: https://github.com/PlatONnetwork/PIPs/blob/master/PIPs/PIP-%s.md
  #Proposal pip_num parameter template
  proposalPipNumTemplate: PIP-%s
  #keysBaseURL
  keyBase: https://keybase.io/
  #keyBase api
  keyBaseApi: _/api/1.0/user/lookup.json?key_suffix=
  #chainid
  chainId: 100
  #Index query paging parameter configuration during synchronization
  paging:
    erc20-transaction:
      pageSize: 2000
      pageCount: 250
  #Redis namespace
  redis-namespace: browser:${profile}
  #Esindex namespace
  es-namespace: browser_${profile}
  #0 Loop access time for block waiting (seconds)
  zeroBlockNumber:
    wait-time: 60

v0150:
  #Effective version of the lock minimum release amount parameter
  restrictingMinimumReleaseActiveVersion: 3584
  #Adjust effective version
  adjustmentActiveVersion: 3840
  #Adjustment proposal ID
  adjustmentPipId: 14
  #Adjustment log output file
  adjustLogFilePath: ./logs/staking-delegate-adjust.log
task:
  #Address statistics task batch size
  addressBatchSize: 1000
  #The adjustment operation is triggered when agent differs by how many block numbers from the actual block number on the chain
  gapForAdjust: 20
  #Unable to catch up with the chain, cache size of ES and Redis in batches
  esRedisNotCatchupBatchSize: 10
  #Has caught up with the chain, batch into the cache size of ES and Redis
  esRedisCatchupBatchSize: 1
xxl:
  job:
    admin:
      #Deployment and address of dispatch center
      addresses: http://192.168.31.110:18080/xxl-job-admin
    #Dispatch center communication TOKEN
    accessToken: qiliu123456
    #Number of days to save dispatch center log files
    logretentiondays: 90
    executor:
      #ExecutorAppName
      appname: turn-scan-agent
      IP: 192.168.31.212
      #Executor port number
      port: 9999
      #Executor running log file storage disk path
      logpath: ./logs/jobhandler
      #Number of days to save executor log files
      logretentiondays: 90
apollo:
  bootstrap:
    # Whether to enable Apollo
    enabled: false
subchain:
  secret: MS672AcBVGhgkiqBbz39YycYB3fET0N6
#Performance configuration
server:
  port: 40030
  tomcat:
    max-connections: 20000
    threads:
      max: 2000
      min-spare: 800
  servlet:
    context-path: /browser-subchain
